### ISSUE TITLE
feat: variabilize CPU and mem docker container parameters depending on the env

### ISSUE THREAD

**Issue by mpailloncy** [jenkins-x/dev-env#77]
**Describe the bug**

I'm getting this error when running for the first time the dev-env container:
```
./dev-env 
checking that the environment file have been created
/home/mpa/.dev-env/.bash_history file doesn't exist, creating...
/home/mpa/.dev-env/.boto file doesn't exist, creating...
/home/mpa/.dev-env/.gitconfig file doesn't exist, creating...
docker: Error response from daemon: Range of CPUs is from 0.01 to 4.00, as there are only 4 CPUs available.
See 'docker run --help'.
```

The number of CPU specified to run the container is 6, but my machine have only 4 available (maybe I need to talk with my employer).
I assume that the same issue could happen with memory, but 8G is probably more common nowadays.

**To Reproduce**
1. Start a dev-env container with less than 6 CPUs available

**Expected behavior**
Should work for machine with less than 6 logical cpu available.

**Desktop (please complete the following information):**
 - OS: Linux - Ubuntu 18.04

**Comment by mpailloncy** [comment]
@cagiti I'm wondering, is there any specific reason to specify cpu/mem in this case? can we just remove those parameters and let the container use what it needs? Did you experience high cpu/mem consumption at some point?

**Comment by mpailloncy** [comment]
Thanks @cagiti, I saw that you have removed --cpus and --memory parameters :+1: 

In my case I'd like the ability to override default WORKSPACE and GO_WORSPACE env vars as well: I opened https://github.com/jenkins-x/dev-env/pull/79

**Comment by cagiti** [comment]
Sorry @mpailloncy, this has been a pet project of mine... but it's awesome that we're getting more users. I'm currently working on golang app which will replace the bash script and then I'm going to determine the cpu and memory

**Comment by mpailloncy** [comment]
no problem at all @cagiti - that's great to have an isolated dev environment with all the tools already installed

**Comment by cagiti** [comment]
cheers @mpailloncy, I welcome all improvements :)

**Comment by mpailloncy** [comment]
I think we can close this one now
