### ISSUE TITLE
Kube config has wrong file path

### ISSUE THREAD

**Issue by warrenbailey** [jenkins-x/dev-env#92]
**Describe the bug**
I'm migrating from a Jenkins X dev environment on my local laptop to using the dev environment. 

I've built the dev-env and it runs. However it's copied over my kube config file and the paths in the file are incorrect, so whenever I run a kubectl command it fails.

**To Reproduce**
Run the dev-env: 
```./dev-env```
Run the following command:
```kc get pods```

**Expected behavior**

The K8 pods are displayed

**Actual Behaviour**
Unable to connect to the server: error executing access token command "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud: no such file or directory output= stderr=

**Desktop (please complete the following information):**
Mac O/S

**Additional context**

**Comment by warrenbailey** [comment]
[config.txt](https://github.com/jenkins-x/dev-env/files/3391657/config.txt)

kube config

**Comment by warrenbailey** [comment]
@cagiti just got round to testing this change and even with the fix I still get the same problem?

**Comment by warrenbailey** [comment]
fixed now

**Comment by surajr3** [comment]
Can U tell me , how did U fix it

**Comment by cagiti** [comment]
when copying the kubeconfig it performs a `sed` command to use the path within the environment
